services:
  postgres-db:
    image: postgres:15.15-alpine3.22
    container_name: postgres-db
    environment:
      POSTGRES_USER: pioges
      POSTGRES_PASSWORD: pioges123
      POSTGRES_DB: pioges_db
    ports:
      - "5432:5432"
  pioges-core-api:
    build:
      context: apps/core-api
      dockerfile: Dockerfile
    container_name: core-api
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db